### ISSUE TITLE
Export observable bundle inconsistent

### ISSUE THREAD

**Issue by openctitest** [LuatixHQ/opencti#2841]
## Description

When I export an observable object with type file on it's data tab, the json bundle created is empty. If I search for that same observable in the main observables list and select the export, the export bundle contains the correct json bundle for the object.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
Centos 7
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
OpenCTI 5.5.2
3. OpenCTI client: { e.g. frontend or python }
frontend
4. Other environment details:
Running as docker containers

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1) Create a new observable of type file
2) Attempt to export it on its Data tab
3) Search for the observable file in the main observables tab
4) Export the bundle

## Expected Output

I would expect both bundles to contain the same data

## Actual Output

Empty bundle on the Data tab

**Comment by SamuelHassine** [comment]
Hello @openctitest,

This has been fixed in 5.5.4.

Kind regards,
Samuel

**Comment by openctitest** [comment]
I upgraded to 5.5.4 and I'm still seeing the issue. Empty export bundle created from the Data tab of the observable object

**Comment by SamuelHassine** [comment]
Hello,

Are you sure your Export STIX connector is running with a token associated to a user with the role "Administrator"? This is not well documented but all export connectors now need to run with a user that has administrator permissions.

It's because export connectors are now impersonating the using requesting the export to avoid data leak so they need to have the "Bypass all" capability to be able to impersonate.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
I've updated documentation:

![image](https://user-images.githubusercontent.com/1334279/218492223-e9be90ec-742c-4676-8e91-dccf213ec3e9.png)

https://filigran.notion.site/Connectors-4586c588462d4a1fb5e661f2d9837db8.
