### ISSUE TITLE
Worker missing reference errors / Inconsistencies / Slow ingestion rate

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#6716]
## Description
I added a new pulse in Alienvault that resulted in about 1.5M Bundles to ingest.
The Ingestion rate was normal at the beginning but then dropped significantly (from about 20 - 30/s to < 1/s). At this time I used 6 Workers.
Currently the only thing I can do is to increase the no of workers significantly to 120 to process these entities as fast as possible (it is slow because of the retry mechanism, not because of data ingestion).

## Environment

1. OS (where OpenCTI server runs): debian (k8s)
2. OpenCTI version: 6.0.9
3. OpenCTI client: python

# LOGS
```json
{"timestamp": "2024-04-17T04:47:30.656736Z", "level": "INFO", "name": "worker", "message": "Message processed, thread terminated", "taskName": null}
{"timestamp": "2024-04-17T04:47:30.657027Z", "level": "INFO", "name": "worker", "message": "Message acknowledged", "taskName": null, "attributes": {"tag": 89}}
{"timestamp": "2024-04-17T04:47:30.658363Z", "level": "INFO", "name": "worker", "message": "Processing a new message, launching a thread...", "taskName": null, "attributes": {"tag": 90}}
{"timestamp": "2024-04-17T04:47:30.659131Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--6bd77f85-7bda-5181-89ad-daf92069486d"}}
{"timestamp": "2024-04-17T04:47:33.128696Z", "level": "INFO", "name": "worker", "message": "Message reprocess", "taskName": null, "attributes": {"tag": 90, "count": 1}}
{"timestamp": "2024-04-17T04:47:33.128987Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--6bd77f85-7bda-5181-89ad-daf92069486d"}}
{"timestamp": "2024-04-17T04:47:34.556683Z", "level": "INFO", "name": "worker", "message": "Message reprocess", "taskName": null, "attributes": {"tag": 90, "count": 2}}
{"timestamp": "2024-04-17T04:47:34.557130Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--6bd77f85-7bda-5181-89ad-daf92069486d"}}
{"timestamp": "2024-04-17T04:47:36.538655Z", "level": "INFO", "name": "worker", "message": "Message reprocess", "taskName": null, "attributes": {"tag": 90, "count": 3}}
{"timestamp": "2024-04-17T04:47:36.539147Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--6bd77f85-7bda-5181-89ad-daf92069486d"}}
{"timestamp": "2024-04-17T04:47:36.586137Z", "level": "WARNING", "name": "worker", "message": "Traceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n", "taskName": null}
{"timestamp": "2024-04-17T04:47:36.586576Z", "level": "INFO", "name": "api", "message": "Report expectation", "taskName": null, "attributes": {"work_id": "work_aabadcd1-3359-4113-bcc5-252c4071c527_2024-04-14T22:55:27.557Z"}}
{"timestamp": "2024-04-17T04:47:36.611395Z", "level": "ERROR", "name": "api", "message": "Cannot report expectation", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/opencti-worker/worker.py\", line 268, in data_handler\n    self.api.stix2.import_bundle_from_json(\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 215, in import_bundle_from_json\n    return self.import_bundle(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2373, in import_bundle\n    self.import_relationship(item, update, types)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1237, in import_relationship\n    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 1132, in import_from_stix2\n    return self.create(\n           ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py\", line 611, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_work.py\", line 56, in report_expectation\n    self.api.query(query, {\"id\": work_id, \"error\": error})\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 351, in query\n    raise ValueError(\nValueError: {'name': 'DATABASE_ERROR', 'message': 'Update indexing fail'}", "taskName": null}
{"timestamp": "2024-04-17T04:47:36.645999Z", "level": "INFO", "name": "worker", "message": "Message processed, thread terminated", "taskName": null}
{"timestamp": "2024-04-17T04:47:36.646270Z", "level": "INFO", "name": "worker", "message": "Message acknowledged", "taskName": null, "attributes": {"tag": 90}}
{"timestamp": "2024-04-17T04:47:36.647599Z", "level": "INFO", "name": "worker", "message": "Processing a new message, launching a thread...", "taskName": null, "attributes": {"tag": 91}}
{"timestamp": "2024-04-17T04:47:36.648342Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--35afd009-4f86-5c29-a246-ccae9eb90a66"}}
{"timestamp": "2024-04-17T04:47:38.249366Z", "level": "INFO", "name": "worker", "message": "Message reprocess", "taskName": null, "attributes": {"tag": 91, "count": 1}}
{"timestamp": "2024-04-17T04:47:38.249828Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--35afd009-4f86-5c29-a246-ccae9eb90a66"}}
{"timestamp": "2024-04-17T04:47:39.571175Z", "level": "INFO", "name": "worker", "message": "Message reprocess", "taskName": null, "attributes": {"tag": 91, "count": 2}}
{"timestamp": "2024-04-17T04:47:39.571494Z", "level": "INFO", "name": "api", "message": "Creating stix_core_relationship", "taskName": null, "attributes": {"relationship_type": "indicates", "from_id": "indicator--abcf801d-742a-528e-bdfe-c70d9bfda6f3", "to_id": "attack-pattern--35afd009-4f86-5c29-a246-ccae9eb90a66"}}
```

**Comment by nino-filigran** [comment]
@iFrozenPhoenix not sure what I can do to help, since there's no repro case or anything. I understand the issue though, don't get me wrong. @Kedae do you have any idea there?

**Comment by ghost** [comment]
additionally I have the following error messages in the error logs in ingestion of the alienvault connector, the ingestions are full of it. It's not always the same entity but always the same error
`{'name': 'UNSUPPORTED_ERROR', 'message': 'Input resolve refs expect single value'}`
```json
{"type": "bundle", "id": "bundle--f90aa034-e61f-4bfa-a509-e4104ebdb11c", "spec_version": "2.1", "x_opencti_seq": 4, "objects": [{"type": "indicator", "spec_version": "2.1", "id": "indicator--650db647-f6b3-50f7-a51c-16a89eb5ebf3", "created_by_ref": "identity--229cfc33-e25d-5ec8-9d7f-0b3d8fc76603", "created": "2024-04-16T09:33:41.129861Z", "modified": "2024-04-16T09:33:41.129861Z", "name": "45.155.91.30", "description": "CC=PH ASN=AS47154 Husam A. H. Hijazi", "pattern": "[ipv4-addr:value = '45.155.91.30']", "pattern_type": "stix", "pattern_version": "2.1", "valid_from": "2024-04-16T09:09:43Z", "object_marking_refs": ["marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"], "x_opencti_main_observable_type": "IPv4-Addr", "x_opencti_score": 50, "nb_deps": 4}]}
```

**Comment by ghost** [comment]
`{'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}`
```json
{"type": "bundle", "id": "bundle--2e9b44a5-5570-4757-9588-0121996b3233", "spec_version": "2.1", "x_opencti_seq": 11, "objects": [{"type": "relationship", "spec_version": "2.1", "id": "relationship--e833ebda-96f0-5377-876d-2a88e9d13fe1", "created_by_ref": "identity--8328ebcc-4b32-5954-9f6e-7d07ed86cd1b", "created": "2024-04-17T12:21:13.017567Z", "modified": "2024-04-17T12:21:13.017567Z", "relationship_type": "targets", "source_ref": "malware--d2d17342-7c91-563c-bb85-a51d5b5c30e4", "target_ref": "identity--f67fbf06-f3cd-58b3-bad9-ed0b4582e8d8", "object_marking_refs": ["marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"], "nb_deps": 11}]}
```
some ingestions of the alienvault connector are also full of this error.

@nino-filigran I don't know, but the errors seem to be because of a common problem and the problem is persistent also in new ingestions of the alienvault connectors data. I can't say for sure but it seems there is a problem with the connector. It is not normal that every single ingestion, even with just 400 bundles contains 100 errors.

**Comment by nino-filigran** [comment]
Ok let me check internally what's going on, and try to find a solution.

**Comment by nino-filigran** [comment]
@Megafredo & @helene-nguyen do you have an idea regarding the error caused by the connector as mentioned in the above comments? (Not talking about the slow ingestion rate here, but really the errors)

**Comment by ghost** [comment]
@nino-filigran probably the issue (Missing Reference Error) is related to https://github.com/OpenCTI-Platform/opencti/issues/6559#issuecomment-2055951880 and partially persists after upgrading to 6.0.10. The ingestion speed is nearly at the normal level again with the normal amount of workers but the error messages are still there. I'm not sure if the Input Resolve Refs Error is related to this, but these two errors are still in the ingestions.
Eventually @SouadHadjiat can say something?
![Screenshot from 2024-04-18 18-36-11](https://github.com/OpenCTI-Platform/opencti/assets/36128722/56476cd2-e749-4041-936f-4a6744dc7600)

**Comment by ghost** [comment]
@nino-filigran any updates on the error? It has developed to a serious problem, at least for me, because all the entities and relations that have this error are not created.

**Comment by nino-filigran** [comment]
@iFrozenPhoenix not yet. I understand the concern though. People tagged on this ticket will anwser when they will have investigated.
In case also adding @pierremahot to see if it's something you're aware of/have some advice.

**Comment by ghost** [comment]
@nino-filigran can you eventually take a look into your internal deployment if you also see this error (especially in the Alienvault connector)?
It would help me to understand the problem. thanks

**Comment by ghost** [comment]
Any updates on this? I would really appreciate it.

**Comment by helene-nguyen** [comment]
@iFrozenPhoenix @nino-filigran we are on it (`MISSING_ERROR_REFERENCE` error) and will give you more details as soon as possible

**Comment by richard-julien** [comment]
I maybe have an idea about this one, due to auto merging and alias management.
Lets talk about it @helene-nguyen

**Comment by helene-nguyen** [comment]
Ok, thanks, I'll schedule a meeting :)

**Comment by helene-nguyen** [comment]
@iFrozenPhoenix after some investigations, the issue will be fixed, we are working on it :)

**Comment by ghost** [comment]
@helene-nguyen cool, happy to hear this 😊. 

Should I open a new issue for the input resolve refs error?

**Comment by helene-nguyen** [comment]
~~If it's different from the initial error, yes please, this way you can follow the updates of this error :)~~

I think it's ok, we can keep this ticket!

**Comment by richard-julien** [comment]
Should be fixed by https://github.com/OpenCTI-Platform/opencti/issues/7020

**Comment by ghost** [comment]
@richard-julien @Kedae I tested it with the current master commit, migration of the alias ids ran successful but the input resolve refs expect single value error persists.

**Comment by richard-julien** [comment]
This fix aims to resolve the missing reference error problem.
The "Input resolve refs expect single value" is a really different problem.
Looks like you have a duplicate id in your platform. Maybe this one "identity--229cfc33-e25d-5ec8-9d7f-0b3d8fc76603".
This situation can happens on same specific race conditions in the data integration. And for older platforms we had also this kind of behavior on some specific failure of elasticsearch that have also fixed.

Can you check with your kibana if you have multiple instances with the "identity--229cfc33-e25d-5ec8-9d7f-0b3d8fc76603" or "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9" id?
If its the case you have to remove one of the duplicate to prevent this error.
