### ISSUE TITLE
[Export] Issue with text/plain exports

### ISSUE THREAD

**Issue by NiQuintin** [LuatixHQ/opencti#6855]
## Description

When performing a simple text/plain export from within a report, an error "_Connector ready to process the operation. This connector only supports list exports_" is displayed. When going to the list export part from report entities on the same report and with the same criteria another error is displayed "_Connector ready to process the operation, a bytes-like object is required, not 'list'_".

## Environment

OpenCTI 6.0.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Export a report in text/plain format (from within the entity),
2. The first error should appear in the data tab,
3. Return to the list of report entities,
4. Select the same report and open the export panel,
5. Start an export from here with the same settings,
6. The second error should appear.

## Expected Output

The report and its contents should be exported in the defined format.

## Actual Output

The connector is ready to process the operation, but is unable to execute it and no export is launched.

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/155080335/a36152b6-f198-4ff9-9af5-13b1559e6b5d)
![image](https://github.com/OpenCTI-Platform/opencti/assets/155080335/2f0984c7-49c4-4ada-bb0e-da2331ae23fa)

**Comment by nino-filigran** [comment]
@NiQuintin On Public demo I could: 
- reproduce the first error message: I've opened the report, clicked on Export, selected Text (max marking TLP Amber). Going to the data section, I had the same error. "Connector ready to process the operation. This connector only supports list exports". I also tried to generate an export directly from the Data tab and got the same (regardless if it's Full export or Simple Export).
- could not reproduce the other bug: I've been to entities, clicked on generate export, selected Text (max marking TLP Amber) and got the export successfully, regardless if it's a full or Simple Export.

However, on Testing I've been able to reproduce both. 
As a result, the first error is already present in production while the other one can should be fixed before it gets to production.

**Comment by richard-julien** [comment]
I think this one is already fixed, @NiQuintin can you retest? thanks

**Comment by NiQuintin** [comment]
@richard-julien it works now from the exports list but I still have the same error from inside the report when I'm doing the export.
![image](https://github.com/OpenCTI-Platform/opencti/assets/155080335/9b4d0bbe-66c7-4a8a-a566-074f5af64c89)

**Comment by richard-julien** [comment]
Its not an error, the connector only supporting exporting list.
If you want to have a single export its more a feature request on the connector side.

**Comment by NiQuintin** [comment]
Okay, it makes sense like that, so it's good for me.

**Comment by emaes** [comment]
I am just getting back to this now… Can you send me an example report/artifac/etc.t that allows me to successfully run the connector without getting the “list export” error/message?  I want to understand what is needed to have a successful run.

**Comment by Jipegien** [comment]
@emaes A text/plain export from a list of entity (like reports) is working now. Note that the connector will only create a list of entity's names (ex.: the list of the name of all reports you've selected).

Closing the ticket as it is not a bug.

If you need an improvement of the connector, feel free to open a feature request issue into the connector repo.
